use_frameworks!

target 'LoadingProgressHUD_Example' do
  platform :ios, '9.0'
  pod 'LoadingProgressHUD', :path => '../'

  target 'LoadingProgressHUD_Tests' do
    inherit! :search_paths

    
  end
end